const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const expected='bb00c71705f0f2ef271000960ffe6b3b8f3cf6b8486d55283e3bc26a2d54146e';
async function query(project,sql){const r=await fetch('https://api.supabase.com/v1/projects/'+project+'/database/query',{method:'POST',headers:{Authorization:'Bearer '+process.env.SUPABASE_ACCESS_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({query:sql}),signal:AbortSignal.timeout(60000),redirect:'error'});if(!r.ok){const detail=await r.text();const first=detail.split(/\\n|\n|CONTEXT:|QUERY:|LINE /)[0].slice(0,450);throw Error('Management query failed HTTP '+r.status+' '+first);}return r.json();}
(async()=>{const bytes=process.env.RR_OFFLINE_TRANSITION_SQL;assert.ok(bytes&&process.env.SUPABASE_ACCESS_TOKEN);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),expected,'Exact reviewed installer required');const sqls=JSON.parse(bytes),evidence=[];
for(const [name,project,rpc,scope] of [['staff','xtzbjlmizmdfqelvhhwx','rr_staff_speed_snapshot','staff-live-20260906'],['phone','pdhnfbrsbpxkmetjkknb','rr_driver_v2_snapshot','driver-live-20260907']]){
 const sql=sqls[name],marker='ReadyRoute offline transition '+crypto.createHash('sha256').update(sql).digest('hex');
 const before=await query(project,"SELECT obj_description(to_regprocedure('public.rr_offline_transition_20260909(jsonb)'),'pg_proc') marker,to_regprocedure('public.rr_offline_transition_20260909(jsonb)') IS NOT NULL installed");
 if(before[0].installed)assert.equal(before[0].marker,marker,'Existing offline function differs');
 if(!before[0].installed){
 const capture=`SELECT public.${rpc}('{"known_version":null}'::jsonb) snapshot,(SELECT to_jsonb(s) FROM rr_ai_control.scopes s WHERE id='${scope}') budget`;
 const guarded=sql.replace("SET LOCAL lock_timeout='5s';",()=>`SET LOCAL lock_timeout='5s'; CREATE TEMP TABLE rr_offline_install_guard ON COMMIT DROP AS ${capture};`).replace('COMMIT;',()=>`DO $guard$ DECLARE current_state jsonb; old_state jsonb; BEGIN SELECT to_jsonb(x) INTO current_state FROM (${capture}) x; SELECT to_jsonb(x) INTO old_state FROM rr_offline_install_guard x; IF current_state IS DISTINCT FROM old_state THEN RAISE EXCEPTION 'Installation altered source or budget'; END IF; END $guard$; COMMENT ON FUNCTION public.rr_offline_transition_20260909(jsonb) IS '${marker}'; COMMIT;`);
 await query(project,guarded);
 }
 const after=(await query(project,"SELECT obj_description(to_regprocedure('public.rr_offline_transition_20260909(jsonb)'),'pg_proc') marker,has_function_privilege('anon','public.rr_offline_transition_20260909(jsonb)','execute') anon,has_function_privilege('authenticated','public.rr_offline_transition_20260909(jsonb)','execute') authenticated,has_function_privilege('service_role','public.rr_offline_transition_20260909(jsonb)','execute') service"))[0];assert.equal(after.marker,marker);assert.equal(after.anon,false);assert.equal(after.authenticated,false);assert.equal(after.service,true);evidence.push({name,...after,source_rows_changed:false});
}
const budgetSql=`BEGIN; SET LOCAL lock_timeout='5s'; LOCK TABLE rr_ai_control.scopes IN SHARE ROW EXCLUSIVE MODE; CREATE TEMP TABLE rr_offline_budget_before ON COMMIT DROP AS SELECT to_jsonb(s) value FROM rr_ai_control.scopes s WHERE id='driver-live-20260907'; DO $b$ BEGIN IF (SELECT count(*) FROM rr_offline_budget_before)<>1 OR (SELECT (value->>'ceiling_nano')::bigint FROM rr_offline_budget_before) NOT IN (5000000000,6000000000) THEN RAISE EXCEPTION 'Unexpected allowance; owner review needed'; END IF; END $b$; UPDATE rr_ai_control.scopes SET ceiling_nano=6000000000 WHERE id='driver-live-20260907'; DO $b$ BEGIN IF (SELECT value-'ceiling_nano' FROM rr_offline_budget_before) IS DISTINCT FROM (SELECT to_jsonb(s)-'ceiling_nano' FROM rr_ai_control.scopes s WHERE id='driver-live-20260907') THEN RAISE EXCEPTION 'Usage or reservations changed'; END IF; END $b$; SELECT ceiling_nano,spent_nano,held_nano FROM rr_ai_control.scopes WHERE id='driver-live-20260907'; COMMIT;`;
const budget=await query('pdhnfbrsbpxkmetjkknb',budgetSql);evidence.push({owner_authorized_driver_allowance:6000000000,prior_usage_and_holds_preserved:true,budget});
fs.mkdirSync('offline-install-evidence',{recursive:true});fs.writeFileSync('offline-install-evidence/result.json',JSON.stringify(evidence,null,2));console.log('Restricted offline append function verified in both databases; no source rows changed.');})().catch(e=>{console.error(e.message);process.exitCode=1});
