#!/usr/bin/env python3
"""Build the driver-used form and physical-artifact coverage ledger."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "knowledge/form_artifact_coverage.csv"

FIELDS = [
    "artifact_id",
    "artifact_name",
    "official_identifiers",
    "artifact_family",
    "driver_use_or_effect",
    "source_ids",
    "backlog_ids",
    "knowledge_ids",
    "artifact_access",
    "procedure_coverage",
    "publication_gate",
    "coverage_limit",
    "required_follow_up",
]


ROWS = [
    {
        "artifact_id": "ART-DEL-001",
        "artifact_name": "Shipment Status Door Tag OP-200/OP-200SP",
        "artifact_family": "DELIVERY_ATTEMPT_FORM",
        "driver_use_or_effect": "Links an attempted or eligible indirect delivery to customer notice, tracking, and proof-of-attempt documentation.",
        "source_ids": "SRC-GDRIVE-FILE-0001;SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-016",
        "knowledge_ids": "KNO-DEL-DOORTAG-001;KNO-DEL-SIG-ISR-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "COMPLETE_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "Current guides establish use and placement, but the current physical form variants are not archived or compared.",
        "required_follow_up": "Acquire current OP-200 and OP-200SP and verify whether their fields and effects differ.",
    },
    {
        "artifact_id": "ART-DEL-002",
        "artifact_name": "Recipient Release Authorization OP-201",
        "artifact_family": "DELIVERY_RELEASE_AUTHORIZATION",
        "driver_use_or_effect": "Controls ordinary commercial recipient-release eligibility and related signature or photo handling.",
        "source_ids": "SRC-GDRIVE-FILE-0008;SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0010;SRC-MGB-PAGE-0011",
        "backlog_ids": "REFSRC-001;REFSRC-017",
        "knowledge_ids": "KNO-DEL-BUS-OP201-001;KNO-DEL-SHIPPER-RELEASE-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "The current form and controlling agreement are missing, and reviewed sources conflict on release without OP-201.",
        "required_follow_up": "Acquire the current OP-201 plus the executed ISP Agreement and resolve the controlling release branch.",
    },
    {
        "artifact_id": "ART-DEL-003",
        "artifact_name": "Signature Release Card OP-206",
        "artifact_family": "DELIVERY_SIGNATURE_FORM",
        "driver_use_or_effect": "Captures a manual delivery signature for one date when technology fails or the customer prefers the card.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-018",
        "knowledge_ids": "KNO-DEL-OP206-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "COMPLETE_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "OP-117 establishes the workflow, but the current card layout and instructions are not acquired.",
        "required_follow_up": "Acquire the current OP-206 and compare its fields and revision to OP-117.",
    },
    {
        "artifact_id": "ART-DEL-004",
        "artifact_name": "Shipment Release Authorization (paper, barcoded, non-barcoded, or digital)",
        "artifact_family": "DELIVERY_RELEASE_AUTHORIZATION",
        "driver_use_or_effect": "Authorizes an eligible ISR release through the form-specific FORGE path.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "",
        "knowledge_ids": "KNO-DEL-SRA-001;KNO-DEL-SIG-ISR-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "COMPLETE_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "Current OP-117 describes all branches, but no separate current sample form is archived.",
        "required_follow_up": "Acquire representative current paper variants and verify barcode/form recognition without changing the source-established workflow.",
    },
    {
        "artifact_id": "ART-DOC-001",
        "artifact_name": "Delivery Record OP-207 (possible driver-shorthand 'Blue Sheet')",
        "artifact_family": "MANUAL_DELIVERY_SHEETING",
        "driver_use_or_effect": "Provides manual delivery sheeting during the OP-117 HAL outage contingency.",
        "source_ids": "SRC-GDRIVE-FILE-0011;SRC-GDRIVE-FILE-0012;SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-004",
        "knowledge_ids": "KNO-DOC-HANDSHEET-001;KNO-DEL-HAL-DELIVERY-001",
        "artifact_access": "PHOTOGRAPHED_EXAMPLE_IDENTITY_UNRESOLVED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "No reviewed source explicitly calls the photographed sheet a Blue Sheet or proves that it is the current OP-207; the images lack publication identity/revision.",
        "required_follow_up": "Acquire the current OP-207, cover/flap instructions, and station-approved outage procedure; verify the colloquial name separately.",
    },
    {
        "artifact_id": "ART-DOC-002",
        "artifact_name": "Delivery Manifest Record OP-207Res",
        "artifact_family": "MANUAL_DELIVERY_SHEETING",
        "driver_use_or_effect": "Provides manual manifest sheeting during the OP-117 HAL outage contingency.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-005",
        "knowledge_ids": "KNO-DOC-HANDSHEET-001;KNO-DEL-HAL-DELIVERY-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "OP-117 names the form but the current record, cover, flap examples, and complete fields are absent.",
        "required_follow_up": "Acquire the current OP-207Res and its complete instructions.",
    },
    {
        "artifact_id": "ART-DOC-003",
        "artifact_name": "OP-117 local Contact Information table",
        "artifact_family": "LOCAL_CONTACT_REFERENCE",
        "driver_use_or_effect": "Provides fill-in fields for service-provider business contacts, authorized officers, the station, alternate numbers, and other locally selected contacts.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "",
        "knowledge_ids": "KNO-INC-ACCIDENT-SCENE-001;KNO-SEC-INCIDENT-REPORT-001;KNO-HAZ-LEAK-001",
        "artifact_access": "CURRENT_ARTIFACT_REVIEWED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "LOCAL_CONFIGURATION_REQUIRED",
        "coverage_limit": "OP-117 page 89 supplies blank contact fields, not the service provider's or station's actual current contact information.",
        "required_follow_up": "Populate and maintain current local contacts through an authorized local configuration; do not publish invented, stale, or private contact details in the shared corpus.",
    },
    {
        "artifact_id": "ART-DOC-004",
        "artifact_name": "FORGE Alternate Signature physical signature record sheet",
        "artifact_family": "MANUAL_SIGNATURE_RECORD",
        "driver_use_or_effect": "Provides the line number and physical signature record referenced by the demonstrated FORGE Alternate Signature workflow.",
        "source_ids": "SRC-GDRIVE-FILE-0008",
        "backlog_ids": "REFSRC-034",
        "knowledge_ids": "KNO-DEL-ALT-SIGNATURE-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "The guide shows selection of a line number from a carried physical signature record but does not identify the current form, full fields, eligibility, custody, or submission rules.",
        "required_follow_up": "Acquire the current official record sheet and instructions; reconcile it with OP-200, ISR/SRA, and OP-207/OP-207Res without assuming they are the same artifact.",
    },
    {
        "artifact_id": "ART-REF-001",
        "artifact_name": "Pickup Reason Codes Card OP-321",
        "artifact_family": "REFERENCE_CARD",
        "driver_use_or_effect": "Defines current reason-code selection conditions for unsuccessful pickups.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-003",
        "knowledge_ids": "KNO-PUP-ZERO-001;KNO-PUP-CALLTAG-NOTREADY-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "OP-117 lists seven reasons but identifies OP-321 as the current card; the card and complete conditions are missing.",
        "required_follow_up": "Acquire current OP-321 and reconcile every pickup-reason entry and operational translation row.",
    },
    {
        "artifact_id": "ART-REF-002",
        "artifact_name": "Service Measurement Status Codes Reference Card OP-324",
        "artifact_family": "REFERENCE_CARD",
        "driver_use_or_effect": "Provides current delivery-status code definitions and selection conditions.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-002;REFSRC-030",
        "knowledge_ids": "KNO-FORGE-STATUS-SCOPE-001;KNO-DEL-NOTATION-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "OP-117 provides a current code table, but the separate OP-324 and 21 definition-only operational workflows remain missing.",
        "required_follow_up": "Acquire current OP-324 and source-specific procedures for all definition-only delivery codes.",
    },
    {
        "artifact_id": "ART-DEL-005",
        "artifact_name": "FXO GHAL Send to QA Label OP-406",
        "artifact_family": "PACKAGE_DISPOSITION_LABEL",
        "driver_use_or_effect": "Marks a post-close FedEx Office HAL refusal for pickup and QA return.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-019",
        "knowledge_ids": "KNO-DEL-HAL-UNABLE-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "The after-close branch is described, but the label and exact QA-return instructions are absent.",
        "required_follow_up": "Acquire current OP-406 and verify who completes, affixes, and receives it.",
    },
    {
        "artifact_id": "ART-HAZ-001",
        "artifact_name": "Hazardous Materials Reminder Card HZ-035",
        "artifact_family": "HAZMAT_REFERENCE_CARD",
        "driver_use_or_effect": "Lists Ground-acceptable/prohibited materials and additional acceptance or handling reminders.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0002",
        "backlog_ids": "REFSRC-006;REFSRC-015",
        "knowledge_ids": "KNO-HAZ-ACCEPTANCE-001;KNO-HAZ-LOAD-PAPERS-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "Current sources repeatedly defer to the card and acceptance table, neither of which is supplied.",
        "required_follow_up": "Acquire current HZ-035 and the current acceptance table; perform hazmat/compliance review.",
    },
    {
        "artifact_id": "ART-HAZ-002",
        "artifact_name": "Hazardous-material reminder card SF-034",
        "artifact_family": "HAZMAT_REFERENCE_CARD",
        "driver_use_or_effect": "Separate current portal-referenced hazmat reminder source.",
        "source_ids": "SRC-MGB-PAGE-0002",
        "backlog_ids": "REFSRC-010",
        "knowledge_ids": "KNO-HAZ-ACCEPTANCE-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The portal identifies the card but its content and relationship to HZ-035 are not available.",
        "required_follow_up": "Acquire SF-034 and determine whether it supersedes, duplicates, or supplements HZ-035.",
    },
    {
        "artifact_id": "ART-HAZ-003",
        "artifact_name": "Safety Information Guide SF-920P",
        "artifact_family": "SAFETY_GUIDE",
        "driver_use_or_effect": "Provides current safety and hazmat training/compliance details referenced by on-road guidance.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0002;SRC-MGB-PAGE-0003",
        "backlog_ids": "REFSRC-007",
        "knowledge_ids": "KNO-HAZ-ACCEPTANCE-001;KNO-HAZ-LOAD-PAPERS-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The current guide is hosted in MyBizAccount and has not been acquired.",
        "required_follow_up": "Acquire the current SF-920P, verify its revision, and reconcile all safety/hazmat records.",
    },
    {
        "artifact_id": "ART-HAZ-004",
        "artifact_name": "Hazardous Materials Labels OP-900LL/OP-900LG",
        "artifact_family": "HAZMAT_PACKAGE_TAG",
        "driver_use_or_effect": "Identifies prepared hazardous-material packages and provides contingency shipping-paper material.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0002",
        "backlog_ids": "REFSRC-012",
        "knowledge_ids": "KNO-HAZ-ACCEPTANCE-001;KNO-HAZ-MANIFEST-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "Current sources describe checks and outage use, but the label artifacts and complete current instructions are missing.",
        "required_follow_up": "Acquire OP-900LL/LG and validate exact fields, removal, custody, and disposal rules.",
    },
    {
        "artifact_id": "ART-HAZ-005",
        "artifact_name": "Hazardous Materials Certification PRP OP-900PRP",
        "artifact_family": "HAZMAT_SHIPPING_PAPER",
        "driver_use_or_effect": "Provides package-specific contingency paperwork when a station manifest is unavailable.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-012;REFSRC-013",
        "knowledge_ids": "KNO-HAZ-MANIFEST-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "OP-117 describes pulling the PRP into an envelope, but the artifact and full current contingency instructions are missing.",
        "required_follow_up": "Acquire the current OP-900PRP and reconcile it with OP-900 and OP-901/902 instructions.",
    },
    {
        "artifact_id": "ART-HAZ-006",
        "artifact_name": "Hazardous Material Envelope OP-901/OP-902",
        "artifact_family": "HAZMAT_DOCUMENT_CONTAINER",
        "driver_use_or_effect": "Keeps required manifest, declarations, and contingency papers accessible during transport.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0002",
        "backlog_ids": "REFSRC-013",
        "knowledge_ids": "KNO-HAZ-MANIFEST-001;KNO-HAZ-LOAD-PAPERS-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "Placement and use are described, but the current envelope variants and exact instructions are absent.",
        "required_follow_up": "Acquire OP-901 and OP-902 and verify vehicle-placement and check-in requirements.",
    },
    {
        "artifact_id": "ART-HAZ-007",
        "artifact_name": "Hazardous Material Certification OP-950 or approved equivalent",
        "artifact_family": "HAZMAT_SHIPPING_PAPER",
        "driver_use_or_effect": "Documents shipper certification needed for regulated hazmat pickup and transport.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0002",
        "backlog_ids": "REFSRC-014",
        "knowledge_ids": "KNO-HAZ-ACCEPTANCE-001;KNO-HAZ-LOAD-PAPERS-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "Required fields are summarized, but the current artifact/equivalent acceptance rules are not fully acquired.",
        "required_follow_up": "Acquire current OP-950 and approved-equivalent guidance; perform compliance review.",
    },
    {
        "artifact_id": "ART-HAZ-008",
        "artifact_name": "Dangerous Goods Declaration or equivalent certification",
        "artifact_family": "HAZMAT_SHIPPING_PAPER",
        "driver_use_or_effect": "May satisfy certification/documentation requirements for dangerous-goods or Ground hazmat shipments when complete.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0002",
        "backlog_ids": "REFSRC-014;REFSRC-015",
        "knowledge_ids": "KNO-HAZ-ACCEPTANCE-001;KNO-HAZ-MANIFEST-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The source permits equivalents but does not establish a complete Ready Route approval test for every form/service.",
        "required_follow_up": "Acquire approved-equivalent criteria and examples and obtain hazmat/compliance review.",
    },
    {
        "artifact_id": "ART-HAZ-009",
        "artifact_name": "Hazardous Materials Manifest",
        "artifact_family": "HAZMAT_VEHICLE_MANIFEST",
        "driver_use_or_effect": "Accounts for regulated hazmat aboard the vehicle and is updated as packages are delivered.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0002",
        "backlog_ids": "REFSRC-008;REFSRC-013",
        "knowledge_ids": "KNO-HAZ-MANIFEST-001;KNO-HAZ-LOAD-PAPERS-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "Ordinary handling is modeled, but relay transfer and full outage/container instructions remain missing.",
        "required_follow_up": "Acquire current manifest examples, relay instructions, and OP-901/902 guidance.",
    },
    {
        "artifact_id": "ART-HAZ-010",
        "artifact_name": "DOT Emergency Response Guidebook (ERG)",
        "artifact_family": "EMERGENCY_REFERENCE_GUIDE",
        "driver_use_or_effect": "Must remain immediately accessible with hazmat paperwork and is consulted for emergency response.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0002",
        "backlog_ids": "REFSRC-031",
        "knowledge_ids": "KNO-HAZ-LOAD-PAPERS-001;KNO-HAZ-LEAK-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The supplied sources require the ERG but do not include the current edition or its response tables.",
        "required_follow_up": "Acquire and version the current approved ERG and preserve it as a separately governed emergency reference.",
    },
    {
        "artifact_id": "ART-HAZ-011",
        "artifact_name": "Special Permit 14691 SF-136",
        "artifact_family": "HAZMAT_EXCEPTION_DOCUMENT",
        "driver_use_or_effect": "Authorizes a narrow return-shipment exception when paired with OP-908.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-020",
        "knowledge_ids": "KNO-HAZ-SF136-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The paired-document effect is described, but the current permit and its precise scope are not acquired.",
        "required_follow_up": "Acquire current SF-136 and verify effective dates, covered defects, and package attachment requirements.",
    },
    {
        "artifact_id": "ART-HAZ-012",
        "artifact_name": "Hazardous Materials Shipper Error Notification OP-908",
        "artifact_family": "HAZMAT_EXCEPTION_DOCUMENT",
        "driver_use_or_effect": "Must accompany SF-136 for the source-described special-permit return branch.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-020",
        "knowledge_ids": "KNO-HAZ-SF136-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The paired-document requirement is described, but the current notification form and fields are absent.",
        "required_follow_up": "Acquire current OP-908 and verify its completion, attachment, and custody procedure.",
    },
    {
        "artifact_id": "ART-HAZ-013",
        "artifact_name": "Hazardous Materials Prohibited/Acceptable Labels Decal 20159S",
        "artifact_family": "HAZMAT_REFERENCE_DECAL",
        "driver_use_or_effect": "Vehicle-mounted aid for identifying prohibited hazardous materials.",
        "source_ids": "SRC-GDRIVE-FILE-0014",
        "backlog_ids": "REFSRC-032",
        "knowledge_ids": "KNO-HAZ-ACCEPTANCE-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "OP-117 identifies the decal and location, but its current content is not supplied.",
        "required_follow_up": "Acquire current 20159S and reconcile it with HZ-035/SF-034 and the acceptance table.",
    },
    {
        "artifact_id": "ART-HAZ-014",
        "artifact_name": "Hazmat Reminder Card SF-035",
        "artifact_family": "HAZMAT_REFERENCE_CARD",
        "driver_use_or_effect": "April 2025 FORGE guide reference for hazmat pickup requirements.",
        "source_ids": "SRC-GDRIVE-FILE-0008",
        "backlog_ids": "REFSRC-033",
        "knowledge_ids": "KNO-HAZ-ACCEPTANCE-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The April 2025 guide names SF-035, while later reviewed sources name HZ-035 and SF-034; the corpus does not establish typo, supersession, duplication, or separate scope.",
        "required_follow_up": "Acquire SF-035 or authoritative identifier history and reconcile it explicitly with HZ-035 and SF-034.",
    },
    {
        "artifact_id": "ART-INC-001",
        "artifact_name": "Accident Packet Instructions for Drivers OP-130",
        "artifact_family": "ACCIDENT_PACKET",
        "driver_use_or_effect": "Provides immediate accident-scene and reporting instructions and is kept in the vehicle glove compartment.",
        "source_ids": "SRC-MGB-PAGE-0006;SRC-MGB-DOC-0006",
        "backlog_ids": "",
        "knowledge_ids": "KNO-INC-ACCIDENT-SCENE-001;KNO-INC-ACCIDENT-REPORT-001",
        "artifact_access": "CURRENT_ARTIFACT_REVIEWED",
        "procedure_coverage": "COMPLETE_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "The current one-page instruction artifact is reviewed; local station and service-provider contact blanks must still be completed.",
        "required_follow_up": "Maintain locally completed contact fields and version-check the packet when the portal changes.",
    },
    {
        "artifact_id": "ART-INC-002",
        "artifact_name": "Passenger in Other Vehicle or Witness Form OP-132",
        "artifact_family": "ACCIDENT_FORM",
        "driver_use_or_effect": "Captures identity, injury, contact, remarks, and signature information from another-vehicle passengers or witnesses.",
        "source_ids": "SRC-MGB-PAGE-0006;SRC-MGB-DOC-0007",
        "backlog_ids": "",
        "knowledge_ids": "KNO-INC-ACCIDENT-SCENE-001",
        "artifact_access": "CURRENT_ARTIFACT_REVIEWED",
        "procedure_coverage": "COMPLETE_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "The current form is reviewed; the passenger or witness completes it with driver assistance.",
        "required_follow_up": "Version-check when the Accident Reporting page changes.",
    },
    {
        "artifact_id": "ART-INC-003",
        "artifact_name": "Accident Report Form OP-135",
        "artifact_family": "ACCIDENT_FORM",
        "driver_use_or_effect": "Records accident, driver, involved-vehicle and occupant, evidence, location, witness, police, site-condition, property-damage, and accident-description/diagram information in the reviewed regions.",
        "source_ids": "SRC-MGB-PAGE-0006;SRC-MGB-DOC-0008",
        "backlog_ids": "",
        "knowledge_ids": "KNO-INC-ACCIDENT-SCENE-001",
        "artifact_access": "CURRENT_ARTIFACT_PARTIALLY_REVIEWED",
        "procedure_coverage": "FORM_FIELDS_PARTIALLY_REVIEWED",
        "publication_gate": "SOURCE_LIMIT_ONLY",
        "coverage_limit": "All five page identities and upper visible regions are durably rendered, but cropped lower regions of pages 2-5 remain unreviewed; the complete field set is not established.",
        "required_follow_up": "Acquire the original PDF or complete page renders and review every cropped region before giving complete form-completion guidance.",
    },
    {
        "artifact_id": "ART-INC-004",
        "artifact_name": "City or state accident report recommended by FedEx",
        "artifact_family": "EXTERNAL_ACCIDENT_FORM",
        "driver_use_or_effect": "May be required in addition to the FedEx accident packet after an incident.",
        "source_ids": "SRC-MGB-DOC-0006",
        "backlog_ids": "",
        "knowledge_ids": "KNO-INC-ACCIDENT-SCENE-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "No jurisdiction-specific form or triggering rule is supplied.",
        "required_follow_up": "Management/compliance must identify the applicable jurisdictional form and current filing requirement for the incident.",
    },
    {
        "artifact_id": "ART-PUP-001",
        "artifact_name": "Call tag label and removable tracking tab",
        "artifact_family": "PICKUP_RETURN_LABEL",
        "driver_use_or_effect": "Re-labels an accepted call-tag return and provides the recipient a tracking reference.",
        "source_ids": "SRC-GDRIVE-FILE-0006;SRC-GDRIVE-FILE-0014",
        "backlog_ids": "",
        "knowledge_ids": "KNO-PUP-CALLTAG-SUCCESS-001;KNO-PUP-CALLTAG-NOTREADY-001;KNO-PUP-CALLTAG-REFUSED-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "COMPLETE_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "Current workflow is modeled, but no standalone physical label specimen is archived.",
        "required_follow_up": "Acquire a current specimen only if exact layout recognition is needed; do not expose sample tracking data.",
    },
    {
        "artifact_id": "ART-VEH-001",
        "artifact_name": "Annual inspection report and inspection decal",
        "artifact_family": "VEHICLE_COMPLIANCE_RECORD",
        "driver_use_or_effect": "Proves a qualifying vehicle passed the required annual inspection within the preceding 12 months.",
        "source_ids": "SRC-MGB-PAGE-0021",
        "backlog_ids": "",
        "knowledge_ids": "KNO-VEH-ANNUAL-INSPECTION-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The portal establishes required fields/evidence and no-use consequence, but no current sample report/decal is archived.",
        "required_follow_up": "Acquire the current accepted report/decal formats and validate jurisdiction/equipment-specific requirements.",
    },
    {
        "artifact_id": "ART-VEH-002",
        "artifact_name": "California 90-day periodic inspection report",
        "artifact_family": "VEHICLE_COMPLIANCE_RECORD",
        "driver_use_or_effect": "Documents California-domiciled regulated P&D vehicle inspection, corrections, and attestation.",
        "source_ids": "SRC-MGB-PAGE-0022",
        "backlog_ids": "",
        "knowledge_ids": "KNO-VEH-CA-90DAY-INSPECTION-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The portal establishes fields and operating restriction, but no report specimen or full legal source set is supplied.",
        "required_follow_up": "Acquire an accepted current form and obtain California compliance review.",
    },
    {
        "artifact_id": "ART-VEH-003",
        "artifact_name": "Roadside inspection report",
        "artifact_family": "VEHICLE_COMPLIANCE_RECORD",
        "driver_use_or_effect": "Documents a roadside inspection and any cited violations for retention and FedEx delivery at the next station.",
        "source_ids": "SRC-MGB-PAGE-0014;SRC-MGB-PAGE-0021",
        "backlog_ids": "REFSRC-011",
        "knowledge_ids": "KNO-DOT-ROADSIDE-REPORT-001;KNO-VEH-PRETRIP-DEFECT-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "FedEx handling is described, but jurisdictional forms and complete violation/correction obligations are not supplied.",
        "required_follow_up": "Acquire applicable current regulatory guidance and preserve the actual report without inferring legal deadlines.",
    },
    {
        "artifact_id": "ART-VEH-004",
        "artifact_name": "Rental agreement and applicable Schedule B evidence",
        "artifact_family": "VEHICLE_AUTHORIZATION_RECORD",
        "driver_use_or_effect": "Shows the rental vehicle's authorized custody/use and relationship to the service provider's approved equipment schedule.",
        "source_ids": "SRC-MGB-DOC-0006;SRC-MGB-PAGE-0020",
        "backlog_ids": "REFSRC-001",
        "knowledge_ids": "KNO-VEH-RENTAL-PREP-001;KNO-HOS-RENTAL-ELD-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "Carriage and vehicle-use branches are described, but the executed agreement/schedule and actual rental document are not supplied.",
        "required_follow_up": "Verify the specific rental agreement, current Schedule B evidence, and applicable ELD/compliance branch before dispatch.",
    },
    {
        "artifact_id": "ART-VEH-005",
        "artifact_name": "Vehicle registration, insurance, inspection, and emissions records",
        "artifact_family": "VEHICLE_COMPLIANCE_RECORD",
        "driver_use_or_effect": "Supports FORGE predispatch validation and legal/contractual vehicle eligibility.",
        "source_ids": "SRC-GDRIVE-FILE-0008;SRC-MGB-PAGE-0014;SRC-MGB-PAGE-0021;SRC-MGB-PAGE-0022",
        "backlog_ids": "REFSRC-011",
        "knowledge_ids": "KNO-FORGE-LOGIN-WARNING-001;KNO-VEH-ANNUAL-INSPECTION-001;KNO-VEH-CA-90DAY-INSPECTION-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "Warning categories and some inspection conditions are known, but current jurisdictional documents and eligibility rules vary.",
        "required_follow_up": "Validate each actual record, jurisdiction, vehicle class, and current compliance requirement before dispatch.",
    },
    {
        "artifact_id": "ART-DRV-001",
        "artifact_name": "Medical examiner certificate/card and qualification records",
        "artifact_family": "DRIVER_COMPLIANCE_RECORD",
        "driver_use_or_effect": "Supports driver-fitness and vehicle-operation eligibility checks at login or roadside inspection.",
        "source_ids": "SRC-GDRIVE-FILE-0008;SRC-MGB-PAGE-0014",
        "backlog_ids": "REFSRC-011;REFSRC-028",
        "knowledge_ids": "KNO-FORGE-LOGIN-WARNING-001;KNO-QUAL-L10-ACTIVATION-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "COMPLIANCE_REVIEW_REQUIRED",
        "coverage_limit": "The corpus identifies warning/document categories but not every current driver/vehicle/jurisdiction requirement.",
        "required_follow_up": "Acquire current qualification forms and applicable regulatory guidance; do not treat a FORGE Continue button as compliance proof.",
    },
    {
        "artifact_id": "ART-SEC-001",
        "artifact_name": "FedEx ID badge or temporary paper badge",
        "artifact_family": "IDENTIFICATION_CREDENTIAL",
        "driver_use_or_effect": "Controls facility access and visible identification while providing FedEx services.",
        "source_ids": "SRC-GDRIVE-FILE-0014;SRC-MGB-PAGE-0007",
        "backlog_ids": "",
        "knowledge_ids": "KNO-SEC-LOST-BADGE-001;KNO-CX-APPEARANCE-001",
        "artifact_access": "GENERIC_DOCUMENT_TYPE_ONLY",
        "procedure_coverage": "COMPLETE_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "Display, temporary-badge, lost-badge, and no-sharing rules are modeled; actual credential templates are intentionally not required for operational guidance.",
        "required_follow_up": "Version-check badge procedures with future security-page changes; do not store credential numbers in the knowledge corpus.",
    },
    {
        "artifact_id": "ART-QUAL-001",
        "artifact_name": "Driving School Evaluation and Guidelines SF-011",
        "artifact_family": "QUALIFICATION_GUIDELINES",
        "driver_use_or_effect": "Defines minimum terms for a driving school seeking qualified Linehaul status.",
        "source_ids": "SRC-MGB-PAGE-0040;SRC-MGB-DOC-0036",
        "backlog_ids": "REFSRC-028",
        "knowledge_ids": "KNO-QUAL-L10-ACTIVATION-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "The parent page identifies the document and submission context, but the complete guidelines are unreviewed and no school-qualification procedure is modeled.",
        "required_follow_up": "Acquire and completely review SRC-MGB-DOC-0036 before using any school requirement or approval criterion.",
    },
    {
        "artifact_id": "ART-QUAL-002",
        "artifact_name": "Driving School Form SF-012",
        "artifact_family": "QUALIFICATION_APPLICATION_FORM",
        "driver_use_or_effect": "Records a school's application and proposed curriculum/training plan for Qualified Linehaul Driving School review.",
        "source_ids": "SRC-MGB-PAGE-0040;SRC-MGB-DOC-0035",
        "backlog_ids": "REFSRC-028",
        "knowledge_ids": "KNO-QUAL-L10-ACTIVATION-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "REFERENCE_ONLY",
        "publication_gate": "HUMAN_REVIEW_REQUIRED",
        "coverage_limit": "The parent page establishes form submission to the facility senior manager, but form fields and complete custody instructions are unreviewed.",
        "required_follow_up": "Acquire and completely review SRC-MGB-DOC-0035 before using form fields or submission details beyond the visible parent-page description.",
    },
    {
        "artifact_id": "ART-QUAL-003",
        "artifact_name": "Qualified Provider Record of Road Test form",
        "artifact_family": "QUALIFICATION_TEST_RECORD",
        "driver_use_or_effect": "Documents the P&D road-test observation and result before candidate assignment.",
        "source_ids": "SRC-MGB-PAGE-0039",
        "backlog_ids": "REFSRC-028",
        "knowledge_ids": "KNO-QUAL-PD-ROADTEST-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "The current page establishes that the applicable Qualified Provider-supplied form is required but does not expose its identifier, revision, fields, route criteria, or completion instructions.",
        "required_follow_up": "Acquire the current applicable form and Qualified Provider instructions; do not invent fields or substitute another test record.",
    },
    {
        "artifact_id": "ART-VEH-006",
        "artifact_name": "Alternative Vehicle Operations Statement of Lease",
        "artifact_family": "VEHICLE_AUTHORIZATION_RECORD",
        "driver_use_or_effect": "Documents the lease to FedEx and requires service-provider and authorized-station signatures before Alternative Vehicle readiness.",
        "source_ids": "SRC-MGB-PAGE-0034;SRC-MGB-DOC-0026",
        "backlog_ids": "REFSRC-040",
        "knowledge_ids": "KNO-VEH-ALT-ONBOARD-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "The parent page establishes completion and both signatures, but the form itself and its fields are unreviewed.",
        "required_follow_up": "Acquire and completely review SRC-MGB-DOC-0026 before using form fields or legal terms.",
    },
    {
        "artifact_id": "ART-VEH-007",
        "artifact_name": "Alternative Vehicle Operations Statement of Sub-Lease",
        "artifact_family": "VEHICLE_AUTHORIZATION_RECORD",
        "driver_use_or_effect": "Documents the conditional lease from the vehicle owner to the service provider when the service provider is not the owner.",
        "source_ids": "SRC-MGB-PAGE-0034;SRC-MGB-DOC-0027",
        "backlog_ids": "REFSRC-040",
        "knowledge_ids": "KNO-VEH-ALT-ONBOARD-001",
        "artifact_access": "DESCRIBED_BUT_NOT_ACQUIRED",
        "procedure_coverage": "PARTIAL_PROCEDURE_MODELED",
        "publication_gate": "VERIFIED_PROCEDURE_WITH_ARTIFACT_GAP",
        "coverage_limit": "The parent page establishes when the form is required, but the form itself and its fields are unreviewed.",
        "required_follow_up": "Acquire and completely review SRC-MGB-DOC-0027 before using form fields or legal terms.",
    },
]


OFFICIAL_IDENTIFIERS = {
    "ART-DEL-001": "OP-200;OP-200SP",
    "ART-DEL-002": "OP-201",
    "ART-DEL-003": "OP-206",
    "ART-DEL-005": "OP-406",
    "ART-DOC-001": "OP-207",
    "ART-DOC-002": "OP-207RES",
    "ART-DRV-001": "",
    "ART-HAZ-001": "HZ-035",
    "ART-HAZ-002": "SF-034",
    "ART-HAZ-003": "SF-920P",
    "ART-HAZ-004": "OP-900;OP-900LL;OP-900LG",
    "ART-HAZ-005": "OP-900PRP",
    "ART-HAZ-006": "OP-901;OP-902",
    "ART-HAZ-007": "OP-950",
    "ART-HAZ-011": "SF-136",
    "ART-HAZ-012": "OP-908",
    "ART-HAZ-013": "20159S",
    "ART-HAZ-014": "SF-035",
    "ART-INC-001": "OP-130",
    "ART-INC-002": "OP-132",
    "ART-INC-003": "OP-135",
    "ART-REF-001": "OP-321",
    "ART-REF-002": "OP-324",
    "ART-QUAL-001": "SF-011",
    "ART-QUAL-002": "SF-012",
}


def build_rows() -> list[dict[str, str]]:
    return sorted(
        [
            {
                **row,
                "official_identifiers": OFFICIAL_IDENTIFIERS.get(row["artifact_id"], ""),
            }
            for row in ROWS
        ],
        key=lambda row: row["artifact_id"],
    )


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(build_rows())
    print(f"wrote {len(ROWS)} form/artifact coverage rows to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
